# Basic
title: Ace Blog
subtitle: Ace Blog
welcome_message: Ace Blog
description: Ace Blog
creator: <a href="blog.ace001.cn">@Ace</a>

url: ""

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: QQ交流, description: QQ交流, url: 'http://wpa.qq.com/msgrd?v=3&uin=215234963&site=qq&menu=yes'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus:ace-blog-1
    # duoshuo: 
    
# Social
social:
    weibo: Ace
    github: Ace
    twitter: Ace
    gplus: 110
    mail: 215234963@qq.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
